
sudo: required
language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
#  - openjdk6



script:
  - mvn clean cobertura:cobertura -Dtest=TruthGwtTest#testCollection -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/truth/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "DZyMubZKulvcV//G+KzszpSqm/tIuZxGuyqUi4swncqcmeGz/z+uEXAHcx8E7NlQ+Fo867emXNyjYWvo5rDcEBgTNfs/4qik+1Y0OnmgP0OFVaZwN0pqppwqSdsNJL525m0JK9WazESH/KV5+zBnyM74SdBGqAe0J/fstKDbB1P1Rxvt1NYPZ6M7kkr2wVw8Muz6DOQ2tJ6w6KY5UiMKk1bsv5c6ib5x7oooj6ym0NIVhLNuMXY0avDp+s+jM8l5CUzSPXriA8UoFNv7LOsLziFj+TMdfjQiJ16Y/yxc7zp4leizhc7bMfvH3/I3jM7v4jx/O2WOBeXh9i7ceQ1WagGL/gGbwe1luGgyn5m5P/NbjtCiOBREF729Q6mQbmym/XRs4QAO5eZ74qWK11OUCofYGQjvvK7QTEmxs5zaFQUYNlsAKJP0Ydad3daVW+sCMV+SrlIR4JMxx5NstNQHi2PFxZvOGaBor9TaxQR6c2QAG+ZzcrH/QHip5o6S33asFdHfoG1hNUY6iecIEhwXdgRHXVVoK5iXI+TysGJx/nfDfm6vEorhYJ42HCa/Q0HIV113ASWJRt8AQGK8ERo6Dja52Cv5fwwsDnhBCwn3K6PhgJOvsC8Yqj91ZJFzvv0d1+kYl4cF/ygPKbnlMvl2NyRLxqiImrVTjsZDONmBboM="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
